[package]
edition = "2018"
name = "rcgen-tests"
publish = false
version = "0.10.0"

[dev-dependencies]
rcgen = { version = "0.11.3", default-features = false }
webpki = { path = "../", default-features = false }
